### ISSUE TITLE
Erase soft deleted reviews

### ISSUE THREAD

**Issue by mouradvt04** [rayyanqcri/rayyan-store#103]
Since the hard delete for archived reviews is now deployed, we need to clean the two rayyan store database instance by removing the soft deleted reviews "rXXXX_YYYY" and their related tables

**Comment by fabubaker** [comment]
https://github.com/rayyanqcri/rayyan-cloud/commit/225cefaaf39ba2e428e5f68cf05da21d485bc9b9 has been deployed.

I'll close the issue when all soft deleted reviews have been dropped.

**Comment by fabubaker** [comment]
Closing this issue since soft deleted reviews have been fully removed.
