### ISSUE TITLE
Inserting dedup results in batches always overwrites the previous batch

### ISSUE THREAD

**Issue by fabubaker** [rayyanqcri/rayyan-store#18]
When attempting to write dedup results in batches, each batch overwrites the previous one. 

For eg: inserting 1050 results with a batch size of 1000 would result in only the last 50 results showing up in the database.

**Comment by fabubaker** [comment]
Not closed until https://github.com/rayyanqcri/rayyan-store/pull/22 is merged.

**Comment by hammady** [comment]
Closed by #22.

**Comment by hammady** [comment]
@fabubaker @mouradvt04 Please test this again on staging.

**Comment by fabubaker** [comment]
Fixed, see screenshot. All dedup results now show up.

![image](https://user-images.githubusercontent.com/9405286/52396473-1755d080-2ac3-11e9-9e41-c05e53d9c58f.png)
