### ISSUE TITLE
Deleting a search returned a server error

### ISSUE THREAD

**Issue by mouradvt04** [rayyanqcri/rayyan-store#20]
When trying to delete a search, the first time I got the message:
"Something went wrong. But rest assured, the Rayyan team has been notified and they will take appropriate action. Please reload this page in a couple of minutes. If the problem persists contact us from the help button in the bottom right and mention this request number: 7de4b684-31e3-4b7a-a42c-a64e8ce3b953"

It worked the second time.

ref: https://rayyan-staging.qcri.org/reviews/21

**Comment by fabubaker** [comment]
This is because of a timeout issue. We think the delete function in RayyanStore takes longer than the timeout. 

A quick fix would be to increase the timeout, but that is simply a band-aid. We're thinking of running the deletion as a background job. Currently investigating.

**Comment by fabubaker** [comment]
Deleting a search involves going through each article and removing the search id from them. We haven't benchmarked anything yet, but we think this is the issue.

**Comment by hammady** [comment]
Here is the staging server log for deleting a search with 2k articles (total 18 seconds > 3 seconds allowed read timeout):

```
2019-02-06 13:19:25 UTC-5c5ade1f.1446c-LOG:  duration: 12156.286 ms
2019-02-06 13:19:25 UTC-5c5ade1f.1446c-LOG:  QUERY STATISTICS
2019-02-06 13:19:25 UTC-5c5ade1f.1446c-DETAIL:  ! system usage stats:
	!	12.156286 elapsed 0.000000 user 0.000000 system sec
	!	[0.000000 user 0.000000 sys total]
2019-02-06 13:19:25 UTC-5c5ade1f.1446c-STATEMENT:  
	      UPDATE r20
	      SET file_ids = file_ids - '32'
	      WHERE file_ids ? '32'
	    
```
And:
```
2019-02-06 13:19:25 UTC-5c5ade1f.1446c-LOG:  statement: 
	      DELETE FROM r20
	      WHERE jsonb_array_length(file_ids) = 0
	    
2019-02-06 13:19:31 UTC-5c5ade1f.1446c-LOG:  duration: 6140.631 ms
2019-02-06 13:19:31 UTC-5c5ade1f.1446c-LOG:  QUERY STATISTICS
2019-02-06 13:19:31 UTC-5c5ade1f.1446c-DETAIL:  ! system usage stats:
	!	6.140631 elapsed 0.000000 user 0.000000 system sec
	!	[0.000000 user 0.000000 sys total]
2019-02-06 13:19:31 UTC-5c5ade1f.1446c-STATEMENT:  
	      DELETE FROM r20
	      WHERE jsonb_array_length(file_ids) = 0
```

**Comment by hammady** [comment]
The solution is to move this to a background job as have been the case for an old deployment of Solr reviews. This will make the search deletion return immediately with no error with the search item disappearing. However, a side effect would be articles not disappearing until after the job finishes. We should send a notification back as previously so that when users click on it, the table will refresh causing articles to disappear.

I think this is tolerable as opposed to appending a where clause to ALL queries to only return non-deleted searches.
