### ISSUE TITLE
Exact Matches

### ISSUE THREAD

**Issue by mouradvt04** [rayyanqcri/rayyan-store#24]
RayyanSolr said 2 “2-exact matches”   in contrast  Rayyan-store said 0; 

I noticed that the content of the notes field of the 2 copies are different.

We need to agree on exact matches (again) and decide what to do with the information that is not matching; I suggest to merge them.

refs: https://rayyan-staging.qcri.org/reviews/22 and https://rayyan.qcri.org/reviews/50479

**Comment by hammady** [comment]
As we agreed before, we have chosen the most conservative approach where the whole article JSON should match to consider it an exact match. So this is the intended behavior.
