### ISSUE TITLE
No publication types reported

### ISSUE THREAD

**Issue by mouradvt04** [rayyanqcri/rayyan-store#25]
No publication types in Rayyan-store, it’s there in RayyanSolr (this could be due to existing publication RayyanSolr).

refs: https://rayyan-staging.qcri.org/reviews/22 and https://rayyan.qcri.org/reviews/50479

**Comment by hammady** [comment]
It is hard to jump between accounts, can you please put more details here? @mouradvt04

**Comment by mouradvt04** [comment]
On RayyanSolr, I get


Journal Article | 2917
-- | --
Issue | 1

On RayyanStore, I get nothing

**Comment by hammady** [comment]
Either it is a bug, or there were previous versions with publication types on Solr.
Are there publication types in the original file?

**Comment by mouradvt04** [comment]
I created a new entry with slight modification of the title so it's counted as new, and Rayyan reports a publication type for that entry. Note that the entry is from a CSV file with no field to "publication type". So it was Rayyan's decision to put it. 
RayyanStore seems to ignore this information.

**Comment by mouradvt04** [comment]
This is not really an issue!
It's due to a weird case where the file had an empty entry which was interpreted differently by RayyanSolr and RayyanStore! 
In RayyanSolr, it was matched to an existing entry (which even had a journal and notes!)
In RayyanStore, it was interpreted as an empty entry with type "journal article".
Since there's only one type, it wasn't displayed in RayyanStore.
