### ISSUE TITLE
Year facet

### ISSUE THREAD

**Issue by mouradvt04** [rayyanqcri/rayyan-store#26]
The values in the year facet are quite different between the RayyanSolr and RayyanStore (this might be due to existing publication RayyanSolr) .

refs: https://rayyan-staging.qcri.org/reviews/22 and https://rayyan.qcri.org/reviews/50479

**Comment by hammady** [comment]
More details here please @mouradvt04

**Comment by mouradvt04** [comment]
On RayyanSolr, I get 

2019 | 1
-- | --
2018 | 18
2017 | 1490
2016 | 1097
2015 | 27
1990 | 8

On RayyanStore, I get

8 | 1
-- | --
77 | 2
7 | 1
34 | 1
29 | 1
22 | 1
2018 | 18
2017 | 1514
2016 | 1104
2015 | 27

Of course, the same file was uploaded in both reviews.
I'm suspecting that the data for the references shown in RayyanSolr predate the upload of this file.

**Comment by hammady** [comment]
You can modify all titles manually before uploading to ensure they end up as brand new articles on Solr.

**Comment by fabubaker** [comment]
I was able to reproduce this using Zbys.csv.

I looked at one of the offending articles (in this case, the sole article with year facet 8).

It looked like this in the .csv file:
```
key,Authors,Title,Journal ,Year ,Abstract,Notes
1278,, Neratinib in HER-2-positive breast cancer: Results to date and clinical usefulness, Therapeutic advances in medical oncology,8(5):339-350.,"The management of HER-2-positive breast cancer has improved significantly with the use of targeted agents to the HER-2 signaling pathway. Despite the improved survival achieved with the use of trastuzumab and chemotherapy in both the adjuvant and metastatic setting, patients may still recur or progress; whilst preclinical data demonstrate that these cancer cells remain addicted to the HER-2 oncogene. Neratinib, an oral small molecule tyrosine-kinase inhibitor has efficacy in the metastatic and adjuvant setting of patients who have previously received trastuzumab-based treatment. Diarrhea, being a class effect of tyrosine-kinase inhibitor, is the most common side effect seen following neratinib administration, but recent data suggests that a prophylactic loperamide regimen can reduce the incidence of grade 3 diarrhea. Phase I through to III clinical trials of neratinib will be reviewed, with discussion of the postulated mechanism underlying diarrheal events and its management. Copyright (C) The Author(s), 2016. ",Screening: E2 - Review/Editorial���  / Notes: Key:  / Second screen: E2 - Review/Editorial���  / Second screen notes:  / Combined decision : E2 - Review/Editorial���  / Inclusion/Exclusion: Exclude / Abstract :  / Citation :  / 
```

If you align the columns, you'll see that the year for this article matches `8(5):339-350.` Is this a proper format for the year?

**Comment by hammady** [comment]
This is the journal format [`volume(issue):page_from-page_to`], but we don't handle it.
The Solr article id is [13204097](https://rayyan.qcri.org/articles/13204097) which is inserted without year information.

**Comment by fabubaker** [comment]
So this is not really a bug? The user input wasn't correct in this case, and that's why it lead to the year facets being mangled.

**Comment by hammady** [comment]
It is not a bug, but the old behavior is better where it detected an invalid date and it was skipped. I believe that was due to postgres date type validation.

**Comment by fabubaker** [comment]
The invalid date is not necessarily skipped in Solr. For instance, see the sole article with year 2019 in the Solr review. It's year column is `16(1).`. But apparently it's registered as 2019 in the facet.

**Comment by mouradvt04** [comment]
If we want to do any cleaning it should be done by the reference parser which could either put the correct value if it can or just put a NULL. 
The example "2019" could be from an pre existing entry.

**Comment by hammady** [comment]
The ref_parser is both lexical and syntax. The semantics are partially handled in rayyan-formats. It is up to Rayyan to accept or reject such values.

**Comment by fabubaker** [comment]
@mouradvt04 Nice find btw, this wasn't necessarily an issue with RayyanStore; the bug was due to code that was written 2 years ago!
