### ISSUE TITLE
Test all admin pages, deprecate tabs and add RayyanStore flag

### ISSUE THREAD

**Issue by hammady** [rayyanqcri/rayyan-store#28]
- Make sure all admin pages work with RayyanStore
- Add RayyanStore boolean flag as read only in admin reviews pages
- Remove deprecated tabs (journals, authors, articles, ...)

**Comment by fabubaker** [comment]
Shouldn't this be closed because of https://github.com/qcri/rayyan/pull/473 and https://github.com/qcri/rayyan/pull/471 ?

**Comment by hammady** [comment]
I will close when I deploy the changes.
