### ISSUE TITLE
Create new analytics endpoints to collect stats from RayyanStore reviews

### ISSUE THREAD

**Issue by hammady** [rayyanqcri/rayyan-store#31]

**Comment by fabubaker** [comment]
Updated list of analytics that throws errors on RayyanStore:

**Trends**:
- [ ] Searches
- [ ] Search Errors
- [ ] Labels

**Top 20**: All of them

**Comment by fabubaker** [comment]
Searches now work because of https://github.com/qcri/rayyan/pull/486.

**Comment by fabubaker** [comment]
Closing this as it's fulfilled by #44.
