### ISSUE TITLE
Failing export to CSV

### ISSUE THREAD

**Issue by mouradvt04** [rayyanqcri/rayyan-store#70]
There are cases where the export fails when selecting CSV. This can be reproduced by login as either rica.ramirez@utsa.edu or m.salah250@yahoo.com and trying an export with the reviews 63733 or  66664.

**Comment by mouradvt04** [comment]
Can be reproduced using any RayyanStore review

**Comment by mouradvt04** [comment]
Few users are complaining about this as the CSV is useful for data manipulation

**Comment by mouradvt04** [comment]
The error in the delayed_job table starts with 
'undefined method `join' for nil:NilClass
Did you mean?  JSON (NoMethodError)'

**Comment by mouradvt04** [comment]
@fabubaker can you please close this and relate it to the fix you did.

**Comment by fabubaker** [comment]
Fixed by https://github.com/rayyanqcri/rayyan-formats-core/pull/6.
