### ISSUE TITLE
Errors with a restored review

### ISSUE THREAD

**Issue by mouradvt04** [rayyanqcri/rayyan-store#88]
A user asked for a review to be restored which I did through the admin interface. Now the review's content is not visible. Three facets showed up and the rest returned a 500 error. 
Trying to recompute total articles (from admin), returns an error (We're sorry, but something went wrong.)
which showed in sentry **https://sentry.io/organizations/rayyan/issues/1335974312/?project=272277&referrer=slack**.

The review is 71296

**Comment by fabubaker** [comment]
Since the review was deleted from RayyanStore, technically it's not possible to restore it. However since we've enabled soft-delete, the review still exists under a different table name.

What's the decision here? I can restore the table in RayyanStore if needed.

**Comment by fabubaker** [comment]
@hammady @mouradvt04 Can I close this?
